name: {{ cookiecutter.project_name }}
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - seaborn
    - pandas
    - scikit-learn
    - pip:
        - tensorflow
